# Generated by Django 6.0.1 on 2026-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='pin',
            field=models.CharField(default='0000', help_text='Clave de 4 dígitos', max_length=4),
        ),
    ]
