# Generated by Django 6.0.1 on 2026-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_giftcard_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='vencida',
            field=models.BooleanField(default=False),
        ),
    ]
