# Generated by Django 6.0.1 on 2026-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_giftcard_vencida'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Cliente'),
        ),
    ]
